#!/bin/bash
#
# updates and initial package install
apt update -y
apt install -qy qemu ebtables dnsmasq-base qemu-kvm libvirt-clients libvirt-daemon-system bridge-utils virt-manager python3-pip
apt install -qy libxslt-dev libxml2-dev libvirt-dev zlib1g-dev ruby-dev
#apt-get build-dep ruby-libvirt
#
# vagrant install
wget https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
dpkg -i vagrant_2.2.9_x86_64.deb
#
# setup nvme drive
parted -a optimal /dev/nvme0n1 mklabel gpt
parted -a optimal /dev/nvme0n1 mkpart primary ext4 0% 100%
sleep 5
mkfs.ext4 /dev/nvme0n1p1
mkdir /mnt/nvme
mount /dev/nvme0n1p1 /mnt/nvme -t ext4
echo "/dev/nvme0n1p1  /mnt/nvme ext4  defaults  0 0" >> /etc/fstab
#
# disable default swap setup 64gb swap on /mnt/nvme
fallocate -l 64G /mnt/nvme/swapfile
chmod 600 /mnt/nvme/swapfile
mkswap /mnt/nvme/swapfile
swapon /mnt/nvme/swapfile
echo "/mnt/nvme/swapfile  none  swap  sw  0 0" >>/etc/fstab
swapoff /dev/sda2
# find UUID of that old swap space so we can comment it out in fstab
SWAP_UUID=`blkid | grep swap | cut -d ' ' -f 2 | cut -d '"' -f 2`
sed -i -e "s/UUID=$SWAP_UUID/#UUID=$SWAP_UUID/" /etc/fstab
#
# change vagrant and libvirt to use nvme
mkdir /mnt/nvme/.libvirt
virsh pool-define-as --name default --type dir --target /mnt/nvme/.libvirt
virsh pool-autostart default
virsh pool-start default
cp -r .vagrant.d/ /mnt/nvme/.vagrant.d
chmod -R 777 /mnt/nvme/.vagrant.d/
export VAGRANT_HOME=/mnt/nvme/.vagrant.d/
echo "export VAGRANT_HOME=/mnt/nvme/.vagrant.d/" >> ~/.bash_profile
#
#
vagrant plugin install vagrant-libvirt
vagrant plugin install vagrant-mutate
#
# install gitlab-runner
curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash
# bug in gitlab-runner install *eyeroll*
sed -i 's/focal/bionic/g' /etc/apt/sources.list.d/runner_gitlab-runner.list 
apt update
apt install gitlab-runner
#
# help gitlab-runner user environment
mkdir /home/gitlab-runner
touch /home/gitlab-runner/.cloud-warnings.skip
echo "export VAGRANT_HOME=/mnt/nvme/.vagrant.d/" >> /home/gitlab-runner/.bash_profile
chown -R gitlab-runner:gitlab-runner /home/gitlab-runner
usermod -d /home/gitlab-runner gitlab-runner
usermod -s /bin/bash gitlab-runner
usermod -G libvirt gitlab-runner
usermod -G libvirt-qemu gitlab-runner
chown -R gitlab-runner:gitlab-runner /mnt/nvme/.vagrant.d/
#
# Other dependencies
pip3 install pydotplus
#
# additional ip addresses on loopback
ip addr add 172.31.255.254/32 dev lo
ip addr add 172.31.255.253/32 dev lo
ip addr add 172.31.255.252/32 dev lo
ip addr add 172.31.255.251/32 dev lo
#
mkdir /mnt/nvme/air-image-builds
chown gitlab-runner:gitlab-runner /mnt/nvme/air-image-builds
# dependencies for virt-clone and all that and also b2
